### ISSUE TITLE
Problems importing articles from WordPress to Ghost

### ISSUE THREAD

**Issue by armandotekoficial** [TryGhost/wp-ghost-exporter#10]
That such friends of Ghost, I have been testing ghost, I liked a lot to be able to migrate a project that I have been working for years, however I had a problem to migrate approximately 1400 articles in wordpress to ghost, however only 288 In addition, it gives me an error of "Import Failed" I have done everything (reinstalled the plugin, cleared cache, timeout in PHP.ini) to be able to solve it until now without success to completely migrate the blog

Note: Additional issue: I am using an azure cloud with Bitnami Ghost preinstalled 
I leave the screenshots :) I would appreciate your help! regards!

![image](https://cloud.githubusercontent.com/assets/17391297/23985943/4546c750-09e7-11e7-9eb9-41e3c9cdc46e.png)

![image](https://cloud.githubusercontent.com/assets/17391297/23985975/66aba56e-09e7-11e7-9c5c-6b11851bf441.png)

![image](https://cloud.githubusercontent.com/assets/17391297/23985980/72b95fd6-09e7-11e7-8ec2-dd5e38779664.png)

**Comment by kirrg001** [comment]
Sorry for late response. If you are still having problems, please raise a new ticket in our [forum](https://forum.ghost.org). Thanks!
