### ISSUE TITLE
Update needed to match current ghost import/export json structure

### ISSUE THREAD

**Issue by michaelreynolds** [TryGhost/wp-ghost-exporter#11]
This plugin needs an update to match the current ghost import/export json structure. Currently upload fails due to json errors.

`
{
	"db": [
		{
			"meta": {
			},
			"data": {
				"migrations": [],
				"migrations_lock": [],
				"posts": [],
				"users": [],
				"posts_authors": [],
				"roles_users": [],
				"permissions": [],
				"permissions_users": [],
				"permissions_roles": [],
				"tags": [],
				"posts_tags": [],
				"apps": [],
				"app_settings": [],
				"app_fields": [],
				"subscribers": [],
				"invites": [],
				"brute": [],
				"webhooks": []
			}
		}
	]
}
`

**Comment by kirrg001** [comment]
> Currently upload fails due to json errors.

Can you please share the error?

**Comment by michaelreynolds** [comment]
It simply says it failed. Sorry, not a very helpful error. 
`Import failed
Import failed due to an unknown error. Check the Web Inspector console and network tabs for errors.`

It could possibly be due to the wp insance I'm working with, the size of the file is 3Mb. But if I try to validate the wp exported json file, it fails.
`Parse error on line 1:
..."html":"<p><a href="\&quot;http:\/\/www
-----------------------^
Expecting 'EOF', '}', ':', ',', ']', got 'undefined'`

But when looking at the file, the json data structure is much different from what is exported from Ghost vs what the plugin exports from WP. 
WP export
`{"data":{"posts":[],"tags":[],"posts_tags":[],"users":[]},"meta":{}}`
Ghost export
`{ "db": [{
	"meta": {},
	"data": {"posts": [],"users": [],"posts_tags": [],"subscribers": [], ... }
	}]
}`

Data mapping on import might be a nice and useful feature. eg. users with a non admin role are actually subscribers.

**Comment by kirrg001** [comment]
Closing. I've raised https://github.com/TryGhost/wp-ghost-exporter/issues/12.
