### ISSUE TITLE
2019 Update

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/wp-ghost-exporter#13]
Hey! We're looking for some help with updating and maintaining this plugin - which is very old and unloved, and could do with a bit of a rewrite/update to support modern versions of Ghost.

When this plugin was created, Ghost was version zero point something and we had a totally different editor and data format - so it doesn't work very well with the latest versions of Ghost anymore.

There are three parts to this:

1. Analyse the current plugin / workflow, and [documentation](https://ghost.org/faq/migrating-from-wordpress-to-ghost/) to come up with a list of problems and improvements.

2. Prioritise and then work through them, working with our developer community lead, @daviddarnes :)

3. Update plugin docs, cut new release, and update in the WP plugin directory

**Comment by karloscarweber** [comment]
👋 Hi, I'm working on this right now.

**Comment by JohnONolan** [comment]
@karloscarweber @nuclearpengy You guys might wanna swap notes with @daviddarnes here, just in case you're doing the same things!

**Comment by daviddarnes** [comment]
Yes please @karloscarweber and @nuclearpengy. Please share what part you're working on and your goals 💟

**Comment by nuclearpengy** [comment]
Hi @daviddarnes.

So far I've:

- forked and cloned the wp exporter
- done an initial (light) code review
- set up a fresh WP instance and loaded some sample content for testing

Next steps I had planned:

- configure fresh Ghost instance for testing the import
- compare the import/export format of the latest release of Ghost with the current WP exporter.
- start working on what needs to be changed/tweaked

@daviddarnes - besides format compatibility, do you have any other "changes" in mind yet? Are you considering making it easier to zip and download media files (even if this is targeted for a point release/iteration)?

@karloscarweber - have you already started implementing changes?

**Comment by daviddarnes** [comment]
This sounds great @nuclearpengy 🎉! Do you mind sharing your findings from your tests? Just to understand the current hurdles to overcome before pressing on.

We want to keep pretty much on the straight and narrow, Posts and Pages. Personally I'd really like media files to get added in as well, but as you said this can be left for a point release. Especially if it's a lot of work.

Keep us posted on your progress. If here is not suitable to talk then feel free to suggest an alternative place.

@karloscarweber if you could let us know your status firstly that would be great 👍

**Comment by badrihippo** [comment]
Hey @daviddarnes and others! I didn't know this maintenance session was going on, but I've just tweaked the script to work for Ghost 2.x (at least for me). Maybe it'll be helpful here?

It doesn't work for Ghost 1.x though, I modified the file directly to change the format. Also, the exported `.json` needs to be run through Ghost's [migrate tool](https://ghost.org/docs/api/v2/migration/#converting-html) before it can be imported which is not ideal.

Anyway, check out pull request #14—hope it helps! I'm not great at PHP but am open to contributing more if there's anything I can do to help :stuck_out_tongue_winking_eye:

**Comment by daviddarnes** [comment]
Howdy @badrihippo! Thanks for contributing 💟. Any contributions like this are welcome, especially if you've been using it on your own projects. I'm guessing these changes were made out of bugs you found from using it? @nuclearpengy has been doing some testing too, your findings will really help with development 🔥

**Comment by badrihippo** [comment]
Thanks @daviddarnes, I'm glad to hear that :smile:

Yes, I'm trying to export my own Wordpress site to Ghost, so these are the fixes I've made during that process. Not thoroughly tested though; I just made sure it's enough to work for me. I'll keep you updated if I come across anything else :mag_right:

**Comment by nuclearpengy** [comment]
Hi @badrihippo - thank you for this. Will check it out. :)

**Comment by nuclearpengy** [comment]
Plugin version 1.0.0 has been released with support for exporting to Ghost 2.x and 3.x and can be downloaded here: https://wordpress.org/plugins/ghost/

Closing.
