### ISSUE TITLE
Upgrade to Wordpress 5.3

### ISSUE THREAD

**Issue by nateBitworks** [TryGhost/wp-ghost-exporter#19]
Upgraded to 5.3 using the Elementor builder. So far noticed that background images are not loading, but will after you reselect them.
![image](https://user-images.githubusercontent.com/56446569/68714213-0b70d080-0565-11ea-96bf-e57dfaab4b73.png)

**Comment by daviddarnes** [comment]
Closing as I believe this isn't related to the WP Ghost exporter plugin

**Comment by nuclearpengy** [comment]
Thanks @daviddarnes. I agree. It doesn't appear to be related to the plugin. 👍

**Comment by nateBitworks** [comment]
It wasn't I messed up posting
