### ISSUE TITLE
unable to import

### ISSUE THREAD

**Issue by Happyfeet01** [TryGhost/wp-ghost-exporter#20]
Hello,

i can´t import to Ghost.

sshadmin@larsmueller:/var/www/ghost$ ghost import /home/sshadmin/*.json
A SystemError occurred.

Message: Import file not found or is not valid JSON

Debug Information:
    OS: Ubuntu, v18.04.3 LTS
    Node Version: v10.17.0
    Ghost Version: 3.1.0
    Ghost-CLI Version: 1.13.1
    Environment: production
    Command: 'ghost import /home/sshadmin/wp_ghost_export.json'

Try running ghost doctor to check your system for known issues.

the JSON File has an Size of  800 MB. Latest Exporter is installed in Windows

**Comment by nuclearpengy** [comment]
Hi @Happyfeet01.

To confirm, is the problem with the WP Exporter or with importing into Ghost?

Have you checked/confirmed that the `.json` file is valid and can open in a text editor?

**Comment by Happyfeet01** [comment]
I use an Json Validator and it’s valid. But the Structure is complete different to the json export file from Ghost. Is the exporter compatible with ghost 3 and Wordpress 5.3?

Export works with Wordpress but no import into Ghost

**Comment by nuclearpengy** [comment]
Thanks for the speedy feedback. 👍 

I've tested with WordPress 5.3 and Ghost 3.1.0 and was able to export 3,576 posts from WordPress and import them into Ghost.

Please check/confirm that you're running the latest version of the plugin and that your Ghost installation has sufficient RAM/Swap space.

**Comment by Happyfeet01** [comment]
Okay thanks for the Feedback. The server has 16 GB RAM, that’s not the problem. Maybe an Browser related thing. I test it tomorrow again.

**Comment by Happyfeet01** [comment]
Okay test it. Don`t work. Can you look at my json file?

**Comment by Happyfeet01** [comment]
Okay. There was an missing } at the end of the json File

**Comment by nuclearpengy** [comment]
hi @Happyfeet01. Thanks for the update. I'm glad it's working now. Did the exporter fail to add the missing `}` or was this caused by something else?
