### ISSUE TITLE
Security: Plugin should not be accessible by Subscribers, Contributors, Authors and maybe Editors

### ISSUE THREAD

**Issue by ksaitor** [TryGhost/wp-ghost-exporter#21]
Here I'm logged in as a Contributor, and I'm able to export someone else's WP site to Ghost. 
Would be great to limit access to only Admins and (maybe) Editors.

![image](https://user-images.githubusercontent.com/936436/82309144-59273380-99f5-11ea-9ddf-7c08c65b9a97.png)

**Comment by nuclearpengy** [comment]
hi @ksaitor - Thank you for raising this issue. Good catch.

**Comment by PaulAdamDavis** [comment]
Closed by #26
