### ISSUE TITLE
Drafts are not exported

### ISSUE THREAD

**Issue by MartinSchmidt123** [TryGhost/wp-ghost-exporter#22]
When using Wordpress Ghost Exporter Plugin in version 1.0.1 with WordPress 5.4.2 then, the exported json-file does not contain the posts with status 'draft'.
This seems to be expected since we do not specify a post_status when using WP_Query. 
The default is 'publish', see https://developer.wordpress.org/reference/classes/wp_query/#status-parameters

We should explicitly filter for the status values that the map_status functions allows, i.e. we need to add 
```
'post_status' => array('publish', 'draft', 'future', 'private', 'pending'),
```
as filter parameter.

**Comment by MartinSchmidt123** [comment]
If we include 'drafts' we also have problems with https://github.com/TryGhost/wp-ghost-exporter/blob/master/class-ghost.php#L362
If published_at is empty (e.g. '') ghost 3.21.0 will complain and use the current data:

> Post: Date is in a wrong format and invalid. It was replaced with the current timestamp.

This is a problem since this means that every draft is never than all the posts. This destroys the whole sorting.
I propose to delete the special treatment for the drafts with respect to the published_at date.

**Comment by PaulAdamDavis** [comment]
The dates issue was addressed in https://github.com/TryGhost/wp-ghost-exporter/issues/25

In my latest testing, exporting drafts is also supported.
