### ISSUE TITLE
Exports post dates in wrong date format

### ISSUE THREAD

**Issue by sjbrg** [TryGhost/wp-ghost-exporter#25]
When trying to import the json file from the Wordpress export I get the following error message for all 100+ posts:

> Post: Date is in a wrong format and invalid. It was replaced with the current timestamp.

The exported json file from Wordpress has the following date format for the field created_at:

`Fri, 30 Mar 2012 11:18:03 +0000`

On the other hand when I tried exporting a post created in Ghost it has this date format:

`2022-01-11T14:50:11.000Z`

It looks though as if the posts still got imported successfully with the correct dates, so I find the error message confusing.

**Comment by PaulAdamDavis** [comment]
Thanks for reporting!

Fixed in https://github.com/TryGhost/wp-ghost-exporter/commit/0960a49ff8fbdaf8d569e3b78125351b1712ba36 and released in 1.0.5
