### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Undefined constant "SECURE_AUTH_COOKIE"

### ISSUE THREAD

**Issue by withinboredom** [TryGhost/wp-ghost-exporter#27]
Activating the plugin results in the entire blog going down due to this error.

WP: 5.9.3
PHP: 8.1

**Comment by PaulAdamDavis** [comment]
This plugin doesn't use a constant called `SECURE_AUTH_COOKIE`. Could you try disabling all other plugins and seeing if you get the same result?

I just tested on WP 5.9.3, PHP 8.0.5, and plugin version 1.0.5 without issue.
