### ISSUE TITLE
Date is in wrong format (PHP <=7)

### ISSUE THREAD

**Issue by davidmytton** [TryGhost/wp-ghost-exporter#28]
Generating an export file for Wordpress running on PHP 7 (which is the default for WordPress.com accounts) results in an invalid date format because the use of `p` in [the date format code](https://github.com/TryGhost/wp-ghost-exporter/blob/3ccbda07f85248e75c0537608c431608ccf1feb2/class-ghost.php#L62) was only added in PHP 8.0. This will result in the error "Post: Date is in a wrong format and invalid. It was replaced with the current timestamp." when importing into Ghost.

The PHP version can be changed in the WordPress.com Hosting Config, but it may be a good idea to add a warning somewhere about this.

**Comment by pearcemichal** [comment]
As a workaround, I have found I am able to open the exported json in visual studio code, and then do a regex find and replace like so:

Find:
```"(.*)T(.*)p"```

Replace:
```: "$1 $2"```

this will replace the T with a space, and get rid of the p, which will then be imported correctly. 

Make sure that the regex and match case options are enabled. 

![image](https://user-images.githubusercontent.com/29542619/178610153-b37989ce-e87a-44d3-8cfa-bf8bfb01dad1.png)

**Comment by PaulAdamDavis** [comment]
Thank you @davidmytton for reporting this! 🙌
It's been addressed and released in version 1.1.1.
