### ISSUE TITLE
Wordpress 6.1.1 - Blog broken after Plugin Activation

### ISSUE THREAD

**Issue by butschi84** [TryGhost/wp-ghost-exporter#30]
As soon as I activate this plugin, my blog is broken (can not be opened anymore) (wordpress 6.1.1 / php 8 / MLPress)

After doing some research i found that the ghost plugin  (ghost.php) calls the "current_user_can" to early, which breaks the blog as soon the plugin is activated in my case. After making the changes mentioned here everything works perfect.
[https://github.com/awesomemotive/google-analytics-for-wordpress/issues/289](https://github.com/awesomemotive/google-analytics-for-wordpress/issues/289)

If you like I cann submit a pullrequest

`[Fri Mar 10 19:14:57.833089 2023] [fcgid:warn] [pid 3283325] [client 213.193.79.30:0] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Undefined constant "SECURE_AUTH_COOKIE" in /home/chmyuserblabla/web/myhomepage.com/public_html/wp-includes/pluggable.php:923
[Fri Mar 10 19:14:57.833161 2023] [fcgid:warn] [pid 3283325] [client 213.193.79.30:0] mod_fcgid: stderr: Stack trace:
[Fri Mar 10 19:14:57.833165 2023] [fcgid:warn] [pid 3283325] [client 213.193.79.30:0] mod_fcgid: stderr: #0 /home/chmyuserblabla/web/myhomepage.com/public_html/wp-includes/pluggable.php(688): wp_parse_auth_cookie(false, '')
[Fri Mar 10 19:14:57.833169 2023] [fcgid:warn] [pid 3283325] [client 213.193.79.30:0] mod_fcgid: stderr: #1 /home/chmyuserblabla/web/myhomepage.com/public_html/wp-includes/class-wp-hook.php(308): wp_validate_auth_cookie(false)
[Fri Mar 10 19:14:57.833172 2023] [fcgid:warn] [pid 3283325] [client 213.193.79.30:0] mod_fcgid: stderr: #2 /home/chmyuserblabla/web/myhomepage.com/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters(false, Array)
[Fri Mar 10 19:14:57.833175 2023] [fcgid:warn] [pid 3283325] [client 213.193.79.30:0] mod_fcgid: stderr: #3 /home/chmyuserblabla/web/myhomepage.com/public_html/wp-includes/user.php(3604): apply_filters('determine_curre...', false)
[Fri Mar 10 19:14:57.833178 2023] [fcgid:warn] [pid 3283325] [client 213.193.79.30:0] mod_fcgid: stderr: #4 /home/chmyuserblabla/web/myhomepage.com/public_html/wp-includes/pluggable.php(70): _wp_get_current_user()
[Fri Mar 10 19:14:57.833181 2023] [fcgid:warn] [pid 3283325] [client 213.193.79.30:0] mod_fcgid: stderr: #5 /home/chmyuserblabla/web/myhomepage.com/public_html/wp-includes/capabilities.php(873): wp_get_current_user()
[Fri Mar 10 19:14:57.833184 2023] [fcgid:warn] [pid 3283325] [client 213.193.79.30:0] mod_fcgid: stderr: #6 /home/chmyuserblabla/web/myhomepage.com/public_html/wp-content/plugins/ghost/ghost.php(33): current_user_can('administrator')
[Fri Mar 10 19:14:57.833187 2023] [fcgid:warn] [pid 3283325] [client 213.193.79.30:0] mod_fcgid: stderr: #7 /home/chmyuserblabla/web/myhomepage.com/public_html/wp-settings.php(392): include_once('/home/chmyuserblabla/...')
[Fri Mar 10 19:14:57.833190 2023] [fcgid:warn] [pid 3283325] [client 213.193.79.30:0] mod_fcgid: stderr: #8 /home/chmyuserblabla/web/myhomepage.com/public_html/wp-config.php(95): require_once('/home/chmyuserblabla/...')
[Fri Mar 10 19:14:57.833199 2023] [fcgid:warn] [pid 3283325] [client 213.193.79.30:0] mod_fcgid: stderr: #9 /home/chmyuserblabla/web/myhomepage.com/public_html/wp-load.php(50): require_once('/home/chmyuserblabla/...')
[Fri Mar 10 19:14:57.833202 2023] [fcgid:warn] [pid 3283325] [client 213.193.79.30:0] mod_fcgid: stderr: #10 /home/chmyuserblabla/web/myhomepage.com/public_html/wp-blog-header.php(13): require_once('/home/chmyuserblabla/...')
[Fri Mar 10 19:14:57.833205 2023] [fcgid:warn] [pid 3283325] [client 213.193.79.30:0] mod_fcgid: stderr: #11 /home/chmyuserblabla/web/myhomepage.com/public_html/index.php(17): require('/home/chmyuserblabla/...')
[Fri Mar 10 19:14:57.833208 2023] [fcgid:warn] [pid 3283325] [client 213.193.79.30:0] mod_fcgid: stderr: #12 {main}
[Fri Mar 10 19:14:57.833211 2023] [fcgid:warn] [pid 3283325] [client 213.193.79.30:0] mod_fcgid: stderr:   thrown in /home/chmyuserblabla/web/myhomepage.com/public_html/wp-includes/pluggable.php on line 923
[Fri Mar 10 19:14:57.972151 2023] [fcgid:warn] [pid 3379869] [client 213.193.79.30:0] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Undefined constant "SECURE_AUTH_COOKIE" in /home/chmyuserblabla/web/myhomepage.com/public_html/wp-includes/pluggable.php:923, referer: https://myhomepage.com/
[Fri Mar 10 19:14:57.972206 2023] [fcgid:warn] [pid 3379869] [client 213.193.79.30:0] mod_fcgid: stderr: Stack trace:, referer: https://myhomepage.com/
[Fri Mar 10 19:14:57.972210 2023] [fcgid:warn] [pid 3379869] [client 213.193.79.30:0] mod_fcgid: stderr: #0 /home/chmyuserblabla/web/myhomepage.com/public_html/wp-includes/pluggable.php(688): wp_parse_auth_cookie(false, ''), referer: https://myhomepage.com/
[Fri Mar 10 19:14:57.972213 2023] [fcgid:warn] [pid 3379869] [client 213.193.79.30:0] mod_fcgid: stderr: #1 /home/chmyuserblabla/web/myhomepage.com/public_html/wp-includes/class-wp-hook.php(308): wp_validate_auth_cookie(false), referer: https://myhomepage.com/
[Fri Mar 10 19:14:57.972216 2023] [fcgid:warn] [pid 3379869] [client 213.193.79.30:0] mod_fcgid: stderr: #2 /home/chmyuserblabla/web/myhomepage.com/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters(false, Array), referer: https://myhomepage.com/
[Fri Mar 10 19:14:57.972220 2023] [fcgid:warn] [pid 3379869] [client 213.193.79.30:0] mod_fcgid: stderr: #3 /home/chmyuserblabla/web/myhomepage.com/public_html/wp-includes/user.php(3604): apply_filters('determine_curre...', false), referer: https://myhomepage.com/
[Fri Mar 10 19:14:57.972223 2023] [fcgid:warn] [pid 3379869] [client 213.193.79.30:0] mod_fcgid: stderr: #4 /home/chmyuserblabla/web/myhomepage.com/public_html/wp-includes/pluggable.php(70): _wp_get_current_user(), referer: https://myhomepage.com/
[Fri Mar 10 19:14:57.972227 2023] [fcgid:warn] [pid 3379869] [client 213.193.79.30:0] mod_fcgid: stderr: #5 /home/chmyuserblabla/web/myhomepage.com/public_html/wp-includes/capabilities.php(873): wp_get_current_user(), referer: https://myhomepage.com/
[Fri Mar 10 19:14:57.972241 2023] [fcgid:warn] [pid 3379869] [client 213.193.79.30:0] mod_fcgid: stderr: #6 /home/chmyuserblabla/web/myhomepage.com/public_html/wp-content/plugins/ghost/ghost.php(33): current_user_can('administrator'), referer: https://myhomepage.com/
[Fri Mar 10 19:14:57.972245 2023] [fcgid:warn] [pid 3379869] [client 213.193.79.30:0] mod_fcgid: stderr: #7 /home/chmyuserblabla/web/myhomepage.com/public_html/wp-settings.php(392): include_once('/home/chmyuserblabla/...'), referer: https://myhomepage.com/
[Fri Mar 10 19:14:57.972248 2023] [fcgid:warn] [pid 3379869] [client 213.193.79.30:0] mod_fcgid: stderr: #8 /home/chmyuserblabla/web/myhomepage.com/public_html/wp-config.php(95): require_once('/home/chmyuserblabla/...'), referer: https://myhomepage.com/
[Fri Mar 10 19:14:57.972251 2023] [fcgid:warn] [pid 3379869] [client 213.193.79.30:0] mod_fcgid: stderr: #9 /home/chmyuserblabla/web/myhomepage.com/public_html/wp-load.php(50): require_once('/home/chmyuserblabla/...'), referer: https://myhomepage.com/
[Fri Mar 10 19:14:57.972254 2023] [fcgid:warn] [pid 3379869] [client 213.193.79.30:0] mod_fcgid: stderr: #10 /home/chmyuserblabla/web/myhomepage.com/public_html/wp-blog-header.php(13): require_once('/home/chmyuserblabla/...'), referer: https://myhomepage.com/
[Fri Mar 10 19:14:57.972257 2023] [fcgid:warn] [pid 3379869] [client 213.193.79.30:0] mod_fcgid: stderr: #11 /home/chmyuserblabla/web/myhomepage.com/public_html/index.php(17): require('/home/chmyuserblabla/...'), referer: https://myhomepage.com/
[Fri Mar 10 19:14:57.972267 2023] [fcgid:warn] [pid 3379869] [client 213.193.79.30:0] mod_fcgid: stderr: #12 {main}, referer: https://myhomepage.com/
[Fri Mar 10 19:14:57.972270 2023] [fcgid:warn] [pid 3379869] [client 213.193.79.30:0] mod_fcgid: stderr:   thrown in /home/chmyuserblabla/web/myhomepage.com/public_html/wp-includes/pluggable.php on line 923, referer: https://myhomepage.com/`

**Comment by PaulAdamDavis** [comment]
Hi @butschi84, thanks for reporting! I can't replicate this, and `SECURE_AUTH_COOKIE` is not used in this codebase, but as this has come up before in https://github.com/TryGhost/wp-ghost-exporter/issues/27  I'm happy to accept a PR!
