### ISSUE TITLE
HTML Entities are not converted

### ISSUE THREAD

**Issue by unitof** [TryGhost/wp-ghost-exporter#31]
HTML Entities in post `titles`, `mobiledoc`, and other fields are not converted, so end up in Ghost as encoded strings like `&amp;` or similar.

Realize this gets a little tricky though, since they _should_ be preserved in, say `href` fields within posts.

**Comment by PaulAdamDavis** [comment]
Fixed in https://github.com/TryGhost/wp-ghost-exporter/pull/32
