### ISSUE TITLE
HTML inside of HTML-tags is converted to Markdown.

### ISSUE THREAD

**Issue by vskjefst** [TryGhost/wp-ghost-exporter#4]
Example:

```
<div class="footnotes">
<h1>Footnotes</h1>
1) Not, it's not "<a href="https://duckduckgo.com/?q=piqued my interest">peaked</a>".
</div>
```

is converted to

```
<div class="footnotes">
# Footnotes
1) Not, it’s not “[peaked](https://duckduckgo.com/?q=piqued my interest)“.
</div>
```

Expected behavior is that the HTML inside the div-element isn't converted, since Markdown inside of HTML-tags isn't parsed, ref. "[Inline HTML](http://daringfireball.net/projects/markdown/syntax#html)"

**Comment by archonia-chris** [comment]
Ran into the same problem. Changed the following to fix it:
lib/html-to-markdown/HTML-To-Markdown.php

`private function convert_children( $node ) {`
`// Don't convert HTML code inside <code> blocks to Markdown - that should stay as HTML`
`if ( self::is_child_of( 'code', $node ) ) {`

->

...
`if ( self::is_child_of( 'code', $node ) || self::is_child_of( 'div', $node ) ) {`

**Comment by nuclearpengy** [comment]
I've tested this use case and I think it's safe to close this issue now.

**Comment by tymoxx** [comment]
ads

**Comment by tymoxx** [comment]
I am migrating the blog from WordPress to Ghost and the posts were not converted to Markdown at all. Do I need to do anything extra the get them converted to Markdown?
