### ISSUE TITLE
Export does not seem to handle code blocks

### ISSUE THREAD

**Issue by pgr0ss** [TryGhost/wp-ghost-exporter#7]
My current wordpress blog uses code blocks that look like:

```
<pre lang="ruby">
def foo
end
</pre>
```

After exporting, this just becomes:

```
 def foo end
```

I also tried blocks like:

```
<code>
def foo
end
</code>
```

This one becomes:

``````
```
<br></br>
def foo<br></br>
end<br></br>`` `` ``
``````

I did notice that inline code blocks work, like `<code>foo</code>`.

Is there a way to properly export my blog posts with code snippets?

On a related note, this plugin seems to use version 2.1.1 of https://github.com/thephpleague/html-to-markdown for converting HTML to Markdown. But that version is several years old and the current version 4.2.1. Perhaps a newer version of the converter might help?

**Comment by pgr0ss** [comment]
Btw, my version of wordpress is `3.8.2+dfsg-1ubuntu0.1`.

**Comment by nuclearpengy** [comment]
`<pre lang="ruby">
def foo
end
</pre>`

now exports/imports as

![Screen Shot 2019-10-06 at 01 18 15](https://user-images.githubusercontent.com/1669838/66261937-41d56600-e7d7-11e9-97b7-0ab9caf47d6d.png)

`<code>
def foo
end
</code>`

Now exports/imports as 

![Screen Shot 2019-10-06 at 01 19 17](https://user-images.githubusercontent.com/1669838/66261940-56196300-e7d7-11e9-9d0c-5a45e66c2e12.png)

So I think this issue should be sorted now.

**Comment by pgr0ss** [comment]
Great, thanks.
